spring:
  datasource:
    url: jdbc:postgresql://postgres:DfGeYhmsffGswPspfSRGJKwXjbKpmBUx@postgres.railway.internal:5432/railway
    username: postgres
    password: DfGeYhmsffGswPspfSRGJKwXjbKpmBUx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: true
